//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mgb.foodstorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class CatBarcodeMap
    {
        public int CategoryId { get; set; }
        public string Barcode { get; set; }
    }
}
