//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mgb.foodstorage
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageThreshold
    {
        public int StorageThresholdId { get; set; }
        public int StoredItemId { get; set; }
        public Nullable<int> Threshold { get; set; }
    }
}
